# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StashSync < Formula
  desc "Sync media files to Kubernetes Stash pod"
  homepage "https://github.com/adampetrovic/stash-sync"
  version "1.3.1"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/adampetrovic/stash-sync/releases/download/v1.3.1/stash-sync_Darwin_x86_64.tar.gz",
      headers: [
        "Authorization: Bearer #{ENV['HOMEBREW_GITHUB_API_TOKEN']}"
      ]
    sha256 "f61d6c0cac1c7efc5f054d6a4484dda6137c1f3b5bc2a632d21fdc3df0fc57a0"

    def install
      bin.install "stash-sync"
    end
  end
  on_arm do
    url "https://github.com/adampetrovic/stash-sync/releases/download/v1.3.1/stash-sync_Darwin_arm64.tar.gz",
      headers: [
        "Authorization: Bearer #{ENV['HOMEBREW_GITHUB_API_TOKEN']}"
      ]
    sha256 "a3ba3ecc9001e9aeaf3d93ffd4c7e9ddf263833f5bc244d2f0c83def42ac4132"

    def install
      bin.install "stash-sync"
    end
  end

  test do
    system "#{bin}/stash-sync --help"
  end
end
