# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StashSync < Formula
  desc "Sync media files to Kubernetes Stash pod"
  homepage "https://github.com/adampetrovic/stash-sync"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/adampetrovic/stash-sync/releases/download/v1.1.0/stash-sync_Darwin_x86_64.tar.gz"
    sha256 "4023038064858d5c554f0054127b1144bf1880d26802a9a40b17c0cf68e54caa"

    def install
      bin.install "stash-sync"
    end
  end
  on_arm do
    url "https://github.com/adampetrovic/stash-sync/releases/download/v1.1.0/stash-sync_Darwin_arm64.tar.gz"
    sha256 "bb71b576f9f5805b74276c8762d1421b922b9d3f374f7aee967d182c000c1213"

    def install
      bin.install "stash-sync"
    end
  end

  test do
    system "#{bin}/stash-sync --help"
  end
end
